spring:
  datasource:
    url: jdbc:mysql://localhost:3306/best?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 123456
center:
  image:
    face: best
  domain: http://localhost:8080/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
